
node ./src/work_queues/new_task.js First message.
node ./src/work_queues/new_task.js Second message..
node ./src/work_queues/new_task.js Third message...
node ./src/work_queues/new_task.js Fourth message....
node ./src/work_queues/new_task.js Fifth message.....